name: clj-kondo
on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "*.adoc"
  pull_request:
    paths-ignore:
      - "*.adoc"

jobs:
  clj-kondo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint template/planck examples
        github_token: ${{ secrets.GITHUB_TOKEN }}
